### PR TITLE
Add method to add mapping range at any time

### LINKED ISSUE #30: Dynamic ViewModelLookup
**Is your feature request related to a problem? Please describe.**
Ability to add to `Dictionary<Type, Type> ViewModelLookup` in multiple places
https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L13C5-L13C77

**My Use case:** We have an app with 100s possibly even a thousand pages, so to manage all the registration and configs, each area/ routes of the app has there own app builder to manage their section, f.e. 
image

Currently in order to add the manual mappings they all need to be initialised at the same time, but in order to keep the code as maintainable as possible i'd like to keep the mapping next to the registrations.

**Describe the solution you'd like**
I see 3 possible solutions using the current code -

- Make `InitialiseViewModelLookup` public and remove `ViewModelLookup.Clear();` (https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L31)
- Make `Dictionary<Type, Type> ViewModelLookup` public so we can manage it ourselves if we'd like (https://github.com/matt-goldman/Maui.Plugins.PageResolver/blob/ff594dae8a38a20d365ca9748214a17df90aa052/src/Maui.Plugins.PageResolver/Resolver.cs#L13C5-L13C77)
- Create a new public method specific to adding to the dictionary

### PR DESCRIPTION
**Pull request by matt-goldman**
Hopefully resolves #30 

Pending feedback from @IeuanWalker

### CODE REVIEW

**Comment by IeuanWalker** [comment]
@matt-goldman Ye all looks good, but could you add another extension method -
```csharp
/// <summary>
/// Adds the specified page to ViewModel mapping to the existing mappings (replaces items with existing key)
/// </summary>
public static void AddViewModelMapping<T1, T2>()
{
    Resolver.ViewModelLookup[typeof(T1)] = typeof(T2);
}
```

Takes my code from looking like this -
image

To this -
image

**Comment by matt-goldman** [comment]
> @matt-goldman Ye all looks good, but could you add another extension method -
> 
> ```cs
> /// <summary>
> /// Adds the specified page to ViewModel mapping to the existing mappings (replaces items with existing key)
> /// </summary>
> public static void AddViewModelMapping<T1, T2>()
> {
>     Resolver.ViewModelLookup[typeof(T1)] = typeof(T2);
> }
> ```
> 
> Takes my code from looking like this - 
> 
> To this - 

Why wouldn't you just do this?

```csharp
public static  MauiAppBuilder RegisterWasteCalendar(this MauiAppBuilder builder)
{
    builder.Services.AddTransient<AddressSearchPage>();
    builder.Services.AddTransient<AddressSearchViewModel>();

    builder.Services.AddTransient<DisplayPage>();
    builder.Services.AddTransient<DisplayViewModel>();

    builder.Services.AddTransient<RemindersPage>();
    builder.Services.AddTransient<RemindersViewModel>();

    builder.Services.AddTransient<AddPopup>();
    builder.Services.AddTransient<AddViewModel>();

    builder.Services.AddTransient<EditPopup>();
    builder.Services.AddTransient<EditViewModel>();

   StartupExtensions.AddViewModelMappings(new Dictionary<type, type>()
   {
        { typeof(AddressSearchPage), typeof(AddressSearchViewModel) },
        { typeof(DisplayPage), typeof(DisplayViewModel) },
        { typeof(RemindersPage), typeof(RemindersViewModel) },
        { typeof(AddPopup), typeof(AddViewModel) },
        { typeof(EditPopup), typeof(EditViewModel) }
   }
}
```

With that said, I have no problem adding the method you're suggesting, although I will probably call it `UpsertViewModelMapping`.

**Comment by matt-goldman** [comment]
@IeuanWalker sorry for the delay. I've added the additional method. Will try to release this weekend.

**Comment by matt-goldman** [comment]
BTW you know the mappings for Display, Reminders, and Address can be auto-generated?

**Comment by IeuanWalker** [comment]
@matt-goldman great thanks :)

Ye i prefer them to be added explicitly, as there are quite a few pages/ services that dont need to be registered. 

So rather than manually register them then remember to add the ignore attribute to the ones not needed

**Pull request merged**
