### PR TITLE
Add InsertPageBefore method to NavigationExtensions

### PR DESCRIPTION
**Pull request by IeuanWalker**
#43

### CODE REVIEW

**Review by matt-goldman — APPROVED** [review]
LGTM! Thanks 😃

**Comment by IeuanWalker** [comment]
@matt-goldman no prob, when do u think u can do a release for it?

**Comment by matt-goldman** [comment]
Bit smashed getting ready for Christmas at the moment (we're hosting) but hopefully before the new year. I want to add the window functionality too.

**Comment by IeuanWalker** [comment]
Haha no prob, enjoy :)

**Comment by matt-goldman** [comment]
@IeuanWalker done - v2.5.2 just got released. Merry Christmas! 🎅🎄

**Comment by IeuanWalker** [comment]
Awesome thanks :)

**Comment by matt-goldman** [comment]
Sorry - 2.5.3

**Pull request merged**
